export default {
    "default.png": require("../antiques/img/default.png"),
    "amphora.png": require("../antiques/img/amphora.png"),
    "black-knight-helm.png": require("../antiques/img/black-knight-helm.png"),
    "medal.png": require("../antiques/img/medal.png"),
    "pocket-watch.png": require("../antiques/img/pocket-watch.png"),
    "lyre.png": require("../antiques/img/lyre.png"),
    "column-vase.png": require("../antiques/img/column-vase.png"),
    "gem-pendant.png": require("../antiques/img/gem-pendant.png"),
    "gladius.png": require("../antiques/img/gladius.png"),
    "hunting-horn.png": require("../antiques/img/hunting-horn.png"),
    "jeweled-chalice.png": require("../antiques/img/jeweled-chalice.png"),
    "jug.png": require("../antiques/img/jug.png"),
    "luger.png": require("../antiques/img/luger.png"),
    "spartan-helmet.png": require("../antiques/img/spartan-helmet.png"),
    "teapot.png": require("../antiques/img/teapot.png"),
    "thor-hammer.png": require("../antiques/img/thor-hammer.png"),
    "umbrella-bayonet.png": require("../antiques/img/umbrella-bayonet.png"),
    "warlord-helmet.png": require("../antiques/img/warlord-helmet.png"),
    "waterskin.png": require("../antiques/img/waterskin.png"),
    "power-ring.png": require("../antiques/img/power-ring.png"),
    "rune-sword.png": require("../antiques/img/rune-sword.png"),
};